var adsManager;var adsLoader;var adDisplayContainer;var intervalTimer;var videoContent;var promiseResolve;var vWidth=640;var vHeight=360;function init(){return new Promise(function(resolve,reject){promiseResolve=resolve;videoContent=document.getElementById('contentElement');setUpIMA()})}
function setUpIMA(){createAdDisplayContainer();adsLoader=new google.ima.AdsLoader(adDisplayContainer);adsLoader.addEventListener(google.ima.AdsManagerLoadedEvent.Type.ADS_MANAGER_LOADED,onAdsManagerLoaded,!1);adsLoader.addEventListener(google.ima.AdErrorEvent.Type.AD_ERROR,onAdError,!1);var contentEndedListener=function(){adsLoader.contentComplete()};videoContent.onended=contentEndedListener;var adsRequest=new google.ima.AdsRequest();adsRequest.adTagUrl='https://pubads.g.doubleclick.net/gampad/ads?'+'sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&'+'impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&'+'cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator=';adsRequest.linearAdSlotWidth=vWidth+40;adsRequest.linearAdSlotHeight=vHeight+40;adsRequest.nonLinearAdSlotWidth=640;adsRequest.nonLinearAdSlotHeight=150;console.warn('adsLoader:',adsLoader);adsLoader.requestAds(adsRequest)}
function createAdDisplayContainer(){adDisplayContainer=new google.ima.AdDisplayContainer(document.getElementById('adContainer'),videoContent)}
function playAds(){videoContent.load();adDisplayContainer.initialize();try{console.log(adsManager);adsManager.init(vWidth,vHeight,google.ima.ViewMode.NORMAL);adsManager.start()}catch(adError){videoContent.play()}}
function onAdsManagerLoaded(adsManagerLoadedEvent){var adsRenderingSettings=new google.ima.AdsRenderingSettings();adsRenderingSettings.restoreCustomPlaybackStateOnAdBreakComplete=!0;adsManager=adsManagerLoadedEvent.getAdsManager(videoContent,adsRenderingSettings);adsManager.addEventListener(google.ima.AdErrorEvent.Type.AD_ERROR,onAdError);adsManager.addEventListener(google.ima.AdEvent.Type.CONTENT_PAUSE_REQUESTED,onContentPauseRequested);adsManager.addEventListener(google.ima.AdEvent.Type.CONTENT_RESUME_REQUESTED,onContentResumeRequested);adsManager.addEventListener(google.ima.AdEvent.Type.ALL_ADS_COMPLETED,onAdEvent);adsManager.addEventListener(google.ima.AdEvent.Type.LOADED,onAdEvent);adsManager.addEventListener(google.ima.AdEvent.Type.STARTED,onAdEvent);adsManager.addEventListener(google.ima.AdEvent.Type.COMPLETE,onAdEvent);playAds()}
function onAdEvent(adEvent){var ad=adEvent.getAd();switch(adEvent.type){case google.ima.AdEvent.Type.LOADED:if(!ad.isLinear()){videoContent.play()}
break;case google.ima.AdEvent.Type.STARTED:if(ad.isLinear()){intervalTimer=setInterval(function(){var remainingTime=adsManager.getRemainingTime()},300)}
break;case google.ima.AdEvent.Type.COMPLETE:promiseResolve('done');if(ad.isLinear()){clearInterval(intervalTimer)}
break}}
function onAdError(adErrorEvent){console.log(adErrorEvent.getError());adsManager.destroy()}
function onContentPauseRequested(){videoContent.pause()}
function onContentResumeRequested(){videoContent.play()}
function getWidth(){return Math.max(document.body.offsetWidth,document.documentElement.offsetWidth,document.documentElement.clientWidth)}